### ISSUE TITLE
关于语音/视频聊天

### ISSUE THREAD

**Issue by MasterOfStar** [heipidage/GcmForMojo#32]
建议加入对语音/视频聊天类消息的支持，在收到此类消息时，直接拉起微信/QQ以使用微信/QQ接电话/视频

**Comment by MasterOfStar** [comment]
另，QQ收到语音消息没有提示

**Comment by THMonster** [comment]
不可能的，webqq没有提供接口

**Comment by MasterOfStar** [comment]
但mojo微信有这功能

**Comment by wl223600** [comment]
这个请到Mojo::Webqq那边反馈一下，gfm这边几乎不对推送消息做任何特殊处理的，基本是服务端推送啥，通知栏就显示啥。
